language: node_js
node_js:
  - "10"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - npm run test
  - ng build --prod

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_API_KEY
  file_glob: true
  file:
    - "dist/**/*"
  on:
    tags: false
