version: 2.1
workflows:
  test_my_app:
    jobs:
      - test
jobs:
  # The test job
  test:
    working_directory: ~/breakpirates-v3
    machine:
      image: ubuntu-2004:202101-01
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      # Install global dependencies
      - run:
          name: Install global dependencies
          command: npm install -g @angular/cli
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
              - node_modules
      # Lint the source code
      - run:
          name: Linting
          command: ng lint
      # Test the source code
      - run:
          name: Testing via Jest
          command: npm run test
      # Build app
      - run:
          name: Building for Production
          command: ng build --prod
