version: 2.1

# Minimal CircleCI config keeping build, test and lint jobs.
# Uses docker executor (faster cold-start than machine) and a single reusable
# install step to avoid duplication. Caches node_modules by package-lock checksum.

executors:
  node: # lightweight node image with npm
    docker:
      - image: cimg/node:18.20-browsers
    working_directory: ~/breakpirates-v3

commands:
  install-deps:
    description: Install node modules and cache them
    steps:
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: Install global CLI
          command: npm install -g @angular/cli
      - run:
          name: Install local dependencies
          command: npm ci
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - install-deps
      - run:
          name: Building for Production
          command: ng build --configuration production

  test:
    executor: node
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - install-deps
      - run:
          name: Testing via Jest
          command: npm run test -- --runInBand

  lint:
    executor: node
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - install-deps
      - run:
          name: Linting
          command: npm run lint

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
