version: 2.1

# Reusable commands
commands:
  # Log the current branch
  current-branch:
    description: "Show current branch"
    steps:
      - run: echo ${CIRCLE_BRANCH}

# Define the jobs we want to run for this project
jobs:
  # The build job
  build:
    working_directory: ~/breakpirates-v3
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      - current-branch:
        name: Show current branch
      # Restore local dependencies from cache
      - restore_cache:
          keys:
          - npm-deps-{{ checksum "package-lock.json" }}
      # Install global dependencies
      - run:
          name: Install global dependencies
          command: npm install -g @angular/cli
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
          paths:
              - node_modules
      # Build app
      - run:
          name: Building for Production
          command: ng build
  # The test job
  test:
    working_directory: ~/breakpirates-v3
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      - current-branch:
        name: Show current branch
      # Restore local dependencies from cache
      - restore_cache:
          keys:
          - npm-deps-{{ checksum "package-lock.json" }}
      # Install global dependencies
      - run:
          name: Install global dependencies
          command: npm install -g @angular/cli
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
          paths:
              - node_modules
      # Test the source code
      - run:
          name: Testing via Jest
          command: npm run test
  # The lint job
  lint:
    working_directory: ~/breakpirates-v3
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      - current-branch:
        name: Show current branch
      # Restore local dependencies from cache
      - restore_cache:
          keys:
          - npm-deps-{{ checksum "package-lock.json" }}
      # Install global dependencies
      - run:
          name: Install global dependencies
          command: npm install -g @angular/cli
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
          paths:
              - node_modules
      # Lint the source code
      - run:
          name: Linting
          command: ng lint

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
