version: 2.1

# Define the jobs we want to run for this project
jobs:
  # The build job
  build:
    working_directory: ~/breakpirates-v3
    machine:
      image: ubuntu-2204:2024.04.4
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys:
          - v1-deps-{{ checksum "package-lock.json" }}
          - v1-deps-
      # Install global dependencies
      - run:
          name: Install global dependencies
          command: npm install -g @angular/cli
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
              - node_modules
      # Build app
      - run:
          name: Building for Production
          command: ng build
  # The test job
  test:
    working_directory: ~/breakpirates-v3
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys:
          - v1-deps-{{ checksum "package-lock.json" }}
          - v1-deps-
      # Install global dependencies
      - run:
          name: Install global dependencies
          command: npm install -g @angular/cli
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
              - node_modules
      # Test the source code
      - run:
          name: Testing via Jest
          command: npm run test
  # The lint job
  lint:
    working_directory: ~/breakpirates-v3
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys:
          - v1-deps-{{ checksum "package-lock.json" }}
          - v1-deps-
      # Install global dependencies
      - run:
          name: Install global dependencies
          command: npm install -g @angular/cli
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
              - node_modules
      # Lint the source code
      - run:
          name: Linting
          command: ng lint

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
